
import Product1 from '../../../static/Product1.png'
export const data = [
    {
        id: "1000",
        image: Product1,
        code: "f230fh0g3",
        name: "Bamboo Watch",
        description: "Product Description",
        price: 65,
        category: "Accessories",
        quantity: 24,
        inventoryStatus: "INSTOCK",
        rating: 5,
    },
    {
        id: "1001",
        image: Product1,
        code: "nvklal433",
        name: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "INSTOCK",
        rating: 4,
    },
    {
        id: "1002",
        image: Product1,
        code: "nvklal433",
        name: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "OUTOFSTOCK",
        rating: 4,
    },
    {
        id: "1003",
        image: Product1,
        code: "nvklal433",
        name: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "OUTOFSTOCK",
        rating: 4,
    },
    {
        id: "1004",
        image: Product1,
        code: "nvklal433",
        name: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "OUTOFSTOCK",
        rating: 4,
    },
    {
        id: "1005",
        image: Product1,
        code: "nvklal433",
        name: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "OUTOFSTOCK",
        rating: 4,
    },
    {
        id: "1006",
        image: Product1,
        code: "nvklal433",
        name: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "OUTOFSTOCK",
        rating: 4,
    },
    {
        id: "1007",
        image: Product1,
        code: "nvklal433",
        name: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "INSTOCK",
        rating: 4,
    },
    {
        id: "1008",
        image: Product1,
        code: "nvklal433",
        name: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "LOWSTOCK",
        rating: 4,
    },
    {
        id: "1009",
        image: Product1,
        code: "nvklal433",
        name: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "OUTOFSTOCK",
        rating: 4,
    },
    {
        id: "1010",
        image: Product1,
        code: "nvklal433",
        name: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "OUTOFSTOCK",
        rating: 4,
    },
    {
        id: "1011",
        image: Product1,
        code: "nvklal433",
        name: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "OUTOFSTOCK",
        rating: 4,
    },
    {
        id: "1012",
        image: Product1,
        code: "nvklal433",
        name: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "LOWSTOCK",
        rating: 4,
    },
    {
        id: "1013",
        image: Product1,
        code: "nvklal433",
        name: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "OUTOFSTOCK",
        rating: 4,
    },
    {
        id: "1014",
        image: Product1,
        code: "nvklal433",
        name: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "OUTOFSTOCK",
        rating: 4,
    },
    {
        id: "1015",
        image: Product1,
        code: "nvklal433",
        name: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "OUTOFSTOCK",
        rating: 4,
    }
]